Add the required hash for `fetchFromGitHub`
When running `nix-shell` it told me
```
error: hash mismatch in fixed-output derivation '/nix/store/lmlnzssnxyky2k7mn7v4yf8mcsj0k7cc-source.drv':
         specified: sha256-AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=
            got:    sha256-ovnhL5otoaACpqHZnk/ucivwtEfBQtGRu4/xw4+Ws+c=
error: 1 dependencies of derivation '/nix/store/zk9zchc381nxbvb7lvsdjn26wgwrhvzb-standard-library-1.5.drv' failed to build
error: build of '/nix/store/hzh8xikpqba95l90zcjrllp65b6b2f3a-agdaWithPackages-2.6.3.drv', '/nix/store/zk9zchc381nxbvb7lvsdjn26wgwrhvzb-standard-library-1.5.drv' failed
```
so there is a missing/default hash (the AAAAA... is the default hash
used in Nix if a hash is unknown or unspecified) in a dependency of
standard-library-1.5 (the only dependency we declared for this package
was the `src` attribute).